apiVersion: v2
name: ourplant
description: Umbrella Helm chart for OurPlant application (frontend, backend, mysql)
type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"

  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"

  - name: mysql
    version: 0.1.0
    repository: "file://charts/mysql"
