apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-backend-to-db
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-backend
    ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-frontend-to-backend
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-frontend
    ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
