global:
  domain: ourplant.local

frontend:
  image:
    repository: abdlerazek/ourplant-frontend
    pullPolicy: Always
    tag: cae57f0af6d6de12eba67115bcaaa0c422960145

  service:
    type: NodePort
    port: 80
    nodePort: 30080
  replicaCount: 1

backend:
  image:
    repository: abdlerazek/ourplant-backend
    tag: cae57f0af6d6de12eba67115bcaaa0c422960145
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
  replicaCount: 1
  env:
    mysqlHost: db
    mysqlUser: root
    mysqlPassword: root
    mysqlDb: ourplant_db

mysql:
  image:
    repository: abdlerazek/ourplant-db
    tag: cae57f0af6d6de12eba67115bcaaa0c422960145
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3306
  replicaCount: 1
  env:
    mysqlRootPassword: root
    mysqlDatabase: ourplant_db
  persistence:
    size: 200Mi


ingress:
  enabled: true
  className: nginx
  path: /
  pathType: Prefix
