{{- if .Values.mysql.limits }}
apiVersion: v1
kind: LimitRange
metadata:
  name: mysql-limits
spec:
  limits:
  - type: {{ .Values.mysql.limits.type | default "Container" }}
    default:
      cpu: {{ .Values.mysql.limits.defaultCpu | default "500m" }}
      memory: {{ .Values.mysql.limits.defaultMemory | default "512Mi" }}
{{- end }}

