apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.mysql.namespace }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.env.mysqlRootPassword | quote }}
  mysql-database: {{ .Values.mysql.env.mysqlDatabase | quote }}
