apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
