apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.mysql.namespace }}
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
