name : ci pipeline
on : 
    push :

        branches : 
            - testing
           
    pull_request :
        branches : 
            - testing

jobs :
  
  codelevel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # -------- SonarCloud --------
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ksami13200_cap-stone-project2
            -Dsonar.organization=ksami13200
            -Dsonar.sources=.

      # -------- Create Report --------
      - name: Export SonarCloud Report
        run: |
          mkdir -p reports
          echo "SonarCloud Report" > reports/sonar-report.txt

          curl -s -u ${{ secrets.SONAR_TOKEN }}: \
          "https://sonarcloud.io/api/measures/component?component=ksami13200_cap-stone-project2&metricKeys=bugs,vulnerabilities,code_smells,coverage" \
          >> reports/sonar-report.txt || echo "Sonar API failed" >> reports/sonar-report.txt

          ls -la reports

      # âœ… UPLOAD HERE (IMPORTANT)
      - name: Upload Sonar Report
        uses: actions/upload-artifact@v4
        with:
          name: sonar-report
          path: reports/



    docker-build-and-push :
        runs-on : ubuntu-latest
        needs : codelevel
        strategy:
            matrix:
              include:
                - service: backend
                  context: .
                  file: ./Dockerfile
                  image: ourplant-backend
                - service: frontend
                  context: .
                  file: ./nginx/Dockerfile
                  image: ourplant-frontend
                - service: database
                  context: ./db
                  file: ./db/Dockerfile
                  image: ourplant-db
        steps :
            - name : Checkout code
              uses : actions/checkout@v4

            - name : login to dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------- Docker Build --------
             # -------- Build Image --------
            - name: Build Docker image
              run: |
                  docker build \
                  -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }} \
                  -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest \
                  -f ${{ matrix.file }} \
                  ${{ matrix.context }}

                        
                 

      # -------- Trivy Scan --------
            - name: Trivy scan image
              uses: aquasecurity/trivy-action@0.33.1
              with:
                image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }}
                scan-type: image
                format: table
                output: reports/trivy-${{ matrix.image }}.txt
                severity: CRITICAL
                ignore-unfixed: true
                exit-code: 1


      # -------- Push Image --------
            - name: Push Docker image (SHA tag)
              run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }}

            - name: Push Docker image (latest tag)
              run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
