permissions:
  contents: write
name : ci pipeline
on : 
    push :

        branches : 
            - testing
           
    pull_request :
        branches : 
            - testing

jobs :
  
  codelevel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # -------- SonarCloud --------
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ksami13200_cap-stone-project2
            -Dsonar.organization=ksami13200
            -Dsonar.sources=.

      # -------- Create Report --------
      - name: Create Sonar Report file
        run: |
            mkdir -p reports
            echo "SonarCloud Report" > reports/sonar-report.txt

            curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "https://sonarcloud.io/api/measures/component?component=ksami13200_cap-stone-project2&metricKeys=bugs,vulnerabilities,code_smells,coverage,security_hotspots" \
            >> reports/sonar-report.txt || echo "Sonar API failed" >> reports/sonar-report.txt




  docker-build-and-push :
        runs-on : ubuntu-latest
        needs : codelevel
        strategy:
            matrix:
              include:
                - service: backend
                  context: .
                  file: ./Dockerfile
                  image: ourplant-backend
                - service: frontend
                  context: .
                  file: ./nginx/Dockerfile
                  image: ourplant-frontend
                - service: database
                  context: ./db
                  file: ./db/Dockerfile
                  image: ourplant-db
        steps :
            - name : Checkout code
              uses : actions/checkout@v4

            - name : login to dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------- Docker Build --------
             # -------- Build Image --------
            - name: Build Docker image
              run: |
                  docker build \
                  -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }} \
                  -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest \
                  -f ${{ matrix.file }} \
                  ${{ matrix.context }}

                        
                 

      # -------- Trivy Scan --------
            - name: Trivy scan image
              uses: aquasecurity/trivy-action@0.33.1
              with:
                  image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }}
                  scan-type: image
                  format: table
                  output: reports/trivy-${{ matrix.image }}.txt
                  severity: CRITICAL
                  ignore-unfixed: true

            - name: Commit & Push reports to repo
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"

                  git add reports/

                  if git diff --cached --quiet; then
                    echo "No changes to commit"
                  else
                    git commit -m "ci: add security & quality reports [skip ci]"
                    git push origin testing
                  fi



      # -------- Push Image --------
            - name: Push Docker image (SHA tag)
              run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }}

            - name: Push Docker image (latest tag)
              run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
