permissions:
  contents: write
name : ci pipeline
on : 
    push :

        branches : 
            - testing
           
    pull_request :
        branches : 
            - testing

jobs :
  
  codelevel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # -------- SonarCloud --------
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ksami13200_cap-stone-project2
            -Dsonar.organization=ksami13200
            -Dsonar.sources=.

      # -------- Create Report --------
      - name: Create Sonar Reports Directory
        run: |
            mkdir -p sonar-reports
            
      - name: Export SonarCloud Reports
        run: |
            PROJECT_KEY="ksami13200_cap-stone-project2"
            AUTH="${{ secrets.SONAR_TOKEN }}:"

            curl -s -u "$AUTH" \
            "https://sonarcloud.io/api/issues/search?componentKeys=$PROJECT_KEY&types=BUG" \
            > sonar-reports/bugs.json

            curl -s -u "$AUTH" \
            "https://sonarcloud.io/api/issues/search?componentKeys=$PROJECT_KEY&types=VULNERABILITY" \
            > sonar-reports/vulnerabilities.json

            curl -s -u "$AUTH" \
            "https://sonarcloud.io/api/issues/search?componentKeys=$PROJECT_KEY&types=CODE_SMELL" \
            > sonar-reports/code_smells.json

            curl -s -u "$AUTH" \
            "https://sonarcloud.io/api/measures/component?component=$PROJECT_KEY&metricKeys=coverage" \
            > sonar-reports/coverage.json

            curl -s -u "$AUTH" \
            "https://sonarcloud.io/api/hotspots/search?projectKey=$PROJECT_KEY" \
            > sonar-reports/security_hotspots.json

      - name: Upload Sonar Reports
        uses: actions/upload-artifact@v4
        with:
            name: sonar-reports
            path: sonar-reports/


  docker-build-and-push :
        runs-on : ubuntu-latest
        needs : codelevel
        strategy:
            matrix:
              include:
                - service: backend
                  context: .
                  file: ./Dockerfile
                  image: ourplant-backend
                - service: frontend
                  context: .
                  file: ./nginx/Dockerfile
                  image: ourplant-frontend
                - service: database
                  context: ./db
                  file: ./db/Dockerfile
                  image: ourplant-db
        steps :
            - name : Checkout code
              uses : actions/checkout@v4

            - name : login to dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------- Docker Build --------
             # -------- Build Image --------
            - name: Build Docker image
              run: |
                  docker build \
                  -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }} \
                  -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest \
                  -f ${{ matrix.file }} \
                  ${{ matrix.context }}

                        
                 

      # -------- Trivy Scan --------
            - name: Trivy scan image
              uses: aquasecurity/trivy-action@0.33.1
              with:
                image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }}
                scan-type: image
                format: table
                severity: CRITICAL
                ignore-unfixed: true
                exit-code: 1

      # -------- Push Image --------
            - name: Push Docker image (SHA tag)
              run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }}

            - name: Push Docker image (latest tag)
              run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
