permissions:
  contents: write
name : ci pipeline
on : 
    push :

        branches : 
            - testing
           
    pull_request :
        branches : 
            - testing

jobs :
  
  codelevel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # -------- SonarCloud --------
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ksami13200_cap-stone-project2
            -Dsonar.organization=ksami13200
            -Dsonar.sources=.

      # -------- Create Report --------
      - name: Save Sonar Results
        run: |
                PROJECT_KEY="Abdelrazek97_cap-stone-project"
                AUTH="${{ secrets.SONAR_TOKEN }}:"

                mkdir -p reports/sonar

                echo "Sonar Summary Report" > reports/sonar/summary.txt
                echo "===================" >> reports/sonar/summary.txt

                echo "Bugs:" >> reports/sonar/summary.txt
                curl -s -u "$AUTH" \
                    "https://sonarcloud.io/api/issues/search?componentKeys=$PROJECT_KEY&types=BUG" \
                    | jq '.total' >> reports/sonar/summary.txt

                echo "Vulnerabilities:" >> reports/sonar/summary.txt
                curl -s -u "$AUTH" \
                    "https://sonarcloud.io/api/issues/search?componentKeys=$PROJECT_KEY&types=VULNERABILITY" \
                    | jq '.total' >> reports/sonar/summary.txt

                echo "Code Smells:" >> reports/sonar/summary.txt
                curl -s -u "$AUTH" \
                    "https://sonarcloud.io/api/issues/search?componentKeys=$PROJECT_KEY&types=CODE_SMELL" \
                    | jq '.total' >> reports/sonar/summary.txt

                STATUS=$(curl -s -u "$AUTH" \
                    "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY" \
                    | jq -r '.projectStatus.status')

                echo "Quality Gate: $STATUS" > reports/sonar/quality-gate.txt



  docker-build-and-push :
        runs-on : ubuntu-latest
        needs : codelevel
        strategy:
            matrix:
              include:
                - service: backend
                  context: .
                  file: ./Dockerfile
                  image: ourplant-backend
                - service: frontend
                  context: .
                  file: ./nginx/Dockerfile
                  image: ourplant-frontend
                - service: database
                  context: ./db
                  file: ./db/Dockerfile
                  image: ourplant-db
        steps :
            - name : Checkout code
              uses : actions/checkout@v4

            - name : login to dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------- Docker Build --------
             # -------- Build Image --------
            - name: Build Docker image
              run: |
                  docker build \
                  -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }} \
                  -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest \
                  -f ${{ matrix.file }} \
                  ${{ matrix.context }}

                        
                 

      # -------- Trivy Scan --------
            - name: Trivy scan image (save to file)
              run: |
                      mkdir -p reports/trivy

                      trivy image \
                        --severity CRITICAL \
                        --ignore-unfixed \
                        --no-progress \
                        ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }} \
                        > reports/trivy/${{ matrix.service }}.txt


      # -------- Push Image --------
            - name: Push Docker image (SHA tag)
              run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }}

            - name: Push Docker image (latest tag)
              run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
